/* Generated by tools/font_json_to_c.py; do not edit. */
#ifndef H__GENERATED_FONTS__
#define H__GENERATED_FONTS__

#include "display_font.h"

extern const display_font_t font_bigfnt;
extern const display_font_t font_bigfntb;
extern const display_font_t font_bigfnti;
extern const display_font_t font_eurex24i;
extern const display_font_t font_hl14;
extern const display_font_t font_hl14b;
extern const display_font_t font_jess14;
extern const display_font_t font_jess14b;
extern const display_font_t font_jess14i;
extern const display_font_t font_swiss20;
extern const display_font_t font_swiss20b;
extern const display_font_t font_swiss20bi;
extern const display_font_t font_swiss20i;

extern const display_font_family_t font_family_bigfnt;
extern const display_font_family_t font_family_eurex24i;
extern const display_font_family_t font_family_hl14;
extern const display_font_family_t font_family_jess14;
extern const display_font_family_t font_family_swiss20;

#endif
