#!/usr/bin/env python3
"""Convert the BDF-like JSON fonts in main/fonts to compact C definitions."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path


def c_identifier(name: str) -> str:
    result = re.sub(r"[^A-Za-z0-9_]", "_", name).lower()
    if not result or result[0].isdigit():
        result = "font_" + result
    return result


def load_font(path: Path) -> dict:
    with path.open(encoding="utf-8") as source:
        font = json.load(source)

    if font.get("schema_version") != 1:
        raise ValueError(f"{path}: unsupported schema_version")
    metrics = font.get("metrics", {})
    height = metrics.get("raster_height")
    baseline = metrics.get("baseline")
    slots = font.get("slots")
    if not isinstance(height, int) or not 0 < height <= 255:
        raise ValueError(f"{path}: invalid raster height")
    if not isinstance(baseline, int) or not 0 <= baseline <= height:
        raise ValueError(f"{path}: invalid baseline")
    if not isinstance(slots, list) or not slots:
        raise ValueError(f"{path}: no glyph slots")

    codes = [slot.get("code") for slot in slots]
    if any(not isinstance(code, int) or not 0 <= code <= 255 for code in codes):
        raise ValueError(f"{path}: character codes must be bytes")
    if len(set(codes)) != len(codes):
        raise ValueError(f"{path}: duplicate character code")
    return font


def encode_font(font: dict, path: Path) -> tuple[list[dict], list[int], int, int]:
    height = font["metrics"]["raster_height"]
    by_code = {slot["code"]: slot for slot in font["slots"]}
    first = min(by_code)
    last = max(by_code)
    glyphs: list[dict] = []
    bitmap: list[int] = []

    for code in range(first, last + 1):
        slot = by_code.get(code)
        if not slot or not slot.get("exists", False):
            glyphs.append({"offset": len(bitmap), "width": 0, "advance": 0,
                           "bearing": 0, "exists": 0})
            continue

        width = slot.get("raster_width")
        advance = slot.get("advance")
        left_kern = slot.get("left_kern")
        rows = slot.get("rows")
        if not isinstance(width, int) or not 0 <= width <= 255:
            raise ValueError(f"{path}: glyph {code} has invalid width")
        if not isinstance(advance, int) or not 0 <= advance <= 255:
            raise ValueError(f"{path}: glyph {code} has invalid advance")
        if not isinstance(left_kern, int) or not -127 <= left_kern <= 128:
            raise ValueError(f"{path}: glyph {code} has invalid left_kern")
        if not isinstance(rows, list) or len(rows) != height:
            raise ValueError(f"{path}: glyph {code} has wrong row count")

        offset = len(bitmap)
        row_bytes = (width + 7) // 8
        for row in rows:
            try:
                value = int(row, 16)
            except (TypeError, ValueError) as error:
                raise ValueError(f"{path}: glyph {code} has an invalid row") from error
            if value < 0 or (width == 0 and value != 0) or (width and value >= (1 << width)):
                raise ValueError(f"{path}: glyph {code} row exceeds its width")
            for byte_index in range(row_bytes):
                shift = max(width - ((byte_index + 1) * 8), 0)
                bits = min(8, width - byte_index * 8)
                byte = (value >> shift) & ((1 << bits) - 1)
                bitmap.append(byte << (8 - bits))

        # In this source format a negative left_kern represents blank space
        # on the left, so the conventional left bearing has the opposite sign.
        glyphs.append({"offset": offset, "width": width, "advance": advance,
                       "bearing": -left_kern, "exists": 1})

    return glyphs, bitmap, first, last


def render(font_paths: list[Path]) -> tuple[str, str]:
    loaded = [(path, load_font(path)) for path in font_paths]
    names = [c_identifier(font["name"]) for _, font in loaded]
    if len(set(names)) != len(names):
        raise ValueError("font names do not produce unique C identifiers")

    header = [
        "/* Generated by tools/font_json_to_c.py; do not edit. */",
        "#ifndef H__GENERATED_FONTS__",
        "#define H__GENERATED_FONTS__",
        "",
        '#include "display_font.h"',
        "",
    ]
    source = [
        "/* Generated by tools/font_json_to_c.py; do not edit. */",
        '#include "fonts/fonts.h"',
        "",
    ]

    for (path, font), name in zip(loaded, names):
        glyphs, bitmap, first, last = encode_font(font, path)
        header.append(f"extern const display_font_t font_{name};")
        source.append(f"static const display_font_glyph_t {name}_glyphs[] = {{")
        for code, glyph in enumerate(glyphs, first):
            source.append(
                "    { %d, %d, %d, %d, %d }, /* 0x%02X */" %
                (glyph["offset"], glyph["width"], glyph["advance"],
                 glyph["bearing"], glyph["exists"], code)
            )
        source.append("};")
        source.append("")
        source.append(f"static const uint8_t {name}_bitmap[] = {{")
        for index in range(0, len(bitmap), 16):
            source.append("    " + ", ".join(f"0x{value:02X}" for value in bitmap[index:index + 16]) + ",")
        source.append("};")
        source.append("")
        fallback = 0x3F if first <= 0x3F <= last and glyphs[0x3F - first]["exists"] else first
        source.extend([
            f"const display_font_t font_{name} = {{",
            f"    .glyphs = {name}_glyphs,",
            f"    .bitmap = {name}_bitmap,",
            f"    .first_character = {first},",
            f"    .glyph_count = {last - first + 1},",
            f"    .height = {font['metrics']['raster_height']},",
            f"    .baseline = {font['metrics']['baseline']},",
            f"    .fallback_character = {fallback},",
            "};",
            "",
        ])

    header.extend(["", "#endif", ""])
    return "\n".join(header), "\n".join(source)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("fonts", nargs="+", type=Path)
    parser.add_argument("--header", required=True, type=Path)
    parser.add_argument("--source", required=True, type=Path)
    parser.add_argument("--check", action="store_true",
                        help="fail if the outputs differ instead of writing them")
    args = parser.parse_args()

    try:
        header, source = render(args.fonts)
    except (OSError, ValueError, json.JSONDecodeError) as error:
        parser.error(str(error))

    outputs = ((args.header, header), (args.source, source))
    if args.check:
        stale = [str(path) for path, contents in outputs
                 if not path.exists() or path.read_text(encoding="utf-8") != contents]
        if stale:
            print("generated font files are stale: " + ", ".join(stale), file=sys.stderr)
            return 1
        return 0

    for path, contents in outputs:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(contents, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
